### PR TITLE
Feature validar login 160036504

### PR DESCRIPTION
**Pull request by Gimli76**
This branch adds an API resource to authenticate google users, and validate their email address against a domain (in this case wyehome.com). The resource returns a json with some user data (used by the frontend to make other API calls) and a Json Web Token, meant to authenticate the user in future API calls. The token and the email address are valid, and if it is the first time the user logs in, a new "profile" is created.

Automatic testing of the /auth API resource proved to be very hard (if not impossible) because the way Google OAuth works (you can not generate the JWT that authenticates google's users without human interaction). So testing this resource was made manually, generating an id_token with [Google OAuth Playground](https://developers.google.com/oauthplayground/), and making a post to the resource with [Postman](https://www.getpostman.com/) (curl is also a good option).
Error testing was done this way as well (with Postman while):
- stopping the DBMS
- turning off the network
- manually modifying google's id_token

Note: A lot of the code of this branch is from branches crear-perfil ad crear-grupo. It was done this way so the User model was available for creation in the firs login. This is not the best way of doing this, but crear-perfil was accepted before this branch (totally my fault for not being able to make this PR sooner). This should not be a big problem once crear-perfil and validar-login are both merged to master and/or development.

### CODE REVIEW

**Comment by LeticiaErrandonea** [comment]
@Gimli76, haven't taken a look at any of what was added but, for the future, please consider opening the PR against the branch from which you had to branch off, so the changes (and commits) are all related to the story. When that branch gets merged, you just change the branch to which this PR points and can get merged 😄 

I'm guessing you branched off `feature-crear-perfil-160060145`. So this PR could point to `feature-crear-perfil-160060145` instead of `master`. Once #6 gets merged, you point to `master` and this can also be merged.

If you have any questions or concerns, please don't doubt to ask.

**Comment by Gimli76** [comment]
Thank you Leticia. I branched off `development` after the PRs of `feature-crear-perfil-160060145` and `feature-crear-grupo-159956714` were accepted and merged (probably not my best idea, I realize). Should I rebase to `feature-crear-perfil-160060145` and make the PR point to it as well?

**Comment by LeticiaErrandonea** [comment]
Ah, okay. Well, in that case I don't think it's a good idea to rebase using `feature-crear-perfil-160060145` as that branch doesn't have the changes from `development`. However, I think sooner or later you'll have to do an ugly rebase to get rid of the commits from the old `development` (with the old implementations of create profile and group) and include the new changes.

**Comment by Gimli76** [comment]
I think I understand.
The other thing that comes to my mind is to start a new branch from `feature-crear-perfil-160060145`, cherry-pick my commits and make the PR again (this way it should end up in the situation you described in your first comment).
I'll leave it as it is for now.

**Comment by LeticiaErrandonea** [comment]
That also works. I'm okay with you leaving it as it is for now, but bear in mind that for the review meeting it should be ready to be merged to `master`.

**Comment by Gimli76** [comment]
Ok. Let me do the cherry-pick thing and the new PR pointing to `feature-crear-perfil-160060145`, should be done in about an hour. Sorry for the mess! :worried:

**Pull request closed without merging**
